CREATE SCHEMA IF NOT EXISTS APPOINTMENT_DB AUTHORIZATION sa;
CREATE TABLE IF NOT EXISTS APPOINTMENT_DB.APPOINTMENT(APPOINTMENTID  INT PRIMARY KEY AUTO_INCREMENT, 
APPOINTMENTDATE VARCHAR(255) , 
STARTTIME VARCHAR(255), 
ENDTIME VARCHAR(255),
SUBJECT VARCHAR(255) ,
DETAILS VARCHAR(255) ,
APPOINTMENTTYPE VARCHAR(255) ,
USERNAME VARCHAR(255) );
